" vim: foldmethod=marker
" vim: foldlevel=0

" my basic conf {{{1
set nocompatible
set incsearch
set ignorecase
set smartcase
set showtabline=2
nnoremap tn :<C-u>tabnew<CR>
nnoremap th :<C-u>tabp<CR>
nnoremap tl :<C-u>tabn<CR>
nnoremap <C-j> <Esc>
cnoremap <C-j> <Esc>
inoremap <C-j> <Esc>
vnoremap <C-j> <Esc>
nnoremap ; :
nnoremap : ;

" neobundle {{{1
if has('vim_starting')
    set runtimepath+=$HOME/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand($HOME . '/.vim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'

"NeoBundle 'Shougo/unite.vim'

call neobundle#end()
filetype plugin indent on
NeoBundleCheck
